INSERT INTO DRIVER (CREATE_TIME, UPDATE_TIME, COMPANY, NAME, DRIVER_ID) VALUES (NOW(), NOW(), '대국통운', '하은용', 1);
INSERT INTO DRIVER (CREATE_TIME, UPDATE_TIME, COMPANY, NAME, DRIVER_ID) VALUES (NOW(), NOW(), '대국통운', '염정현', 2);
INSERT INTO DRIVER (CREATE_TIME, UPDATE_TIME, COMPANY, NAME, DRIVER_ID) VALUES (NOW(), NOW(), '대국통운', '임세현', 3);
INSERT INTO DRIVER (CREATE_TIME, UPDATE_TIME, COMPANY, NAME, DRIVER_ID) VALUES (NOW(), NOW(), '한민화물운송', '임준영', 4);
INSERT INTO DRIVER (CREATE_TIME, UPDATE_TIME, COMPANY, NAME, DRIVER_ID) VALUES (NOW(), NOW(), '한민화물운송', '이동규', 5);

INSERT INTO Vendor (CREATE_TIME, UPDATE_TIME, NAME, CHARGE_NAME, CHARGE_PHONE, VENDOR_ID) VALUES (NOW(), NOW(), '마크컬리','김영업', '010999999999', 1);
INSERT INTO Vendor (CREATE_TIME, UPDATE_TIME, NAME, CHARGE_NAME, CHARGE_PHONE, VENDOR_ID) VALUES (NOW(), NOW(), '팡쿠','김영업', '010999999999', 2);
INSERT INTO Vendor (CREATE_TIME, UPDATE_TIME, NAME, CHARGE_NAME, CHARGE_PHONE, VENDOR_ID) VALUES (NOW(), NOW(), '새벽야채','김영업', '010999999999', 3);
INSERT INTO Vendor (CREATE_TIME, UPDATE_TIME, NAME, CHARGE_NAME, CHARGE_PHONE, VENDOR_ID) VALUES (NOW(), NOW(), '빠른과일','박영업', '010888888888', 4);
INSERT INTO Vendor (CREATE_TIME, UPDATE_TIME, NAME, CHARGE_NAME, CHARGE_PHONE, VENDOR_ID) VALUES (NOW(), NOW(), '오늘수산물','박영업', '010888888888', 5);

